### ISSUE TITLE
Node fetching error in json

### ISSUE THREAD

**Issue by hichtakk** [Mirantis/k8s-externalipcontroller#128]
After repeating these action below, I faced a problem.

* annotate external-ip:auto to service
* delete service
* create service and annotate again

External IP is allocated but loopback address doesn't configured and
other ipclaims aren't rescheduled.
Controller log saids,

```
controller.go:174] Error fetching node node-002 : json: cannot unmarshal number 1e+06 into Go value of type int64
```

Is there any way to solve this problem?

**Comment by AlexeyKasatkin** [comment]
@hichtakk , thank you for the feedback. I'll check this sequence.
Do you have this error (in controller log) repeated regularly or not?
The error points to some IPNode data inconsistency.
Please show, what "kubectl get ipnode" says to you.

"loopback address doesn't configured" - do you mean that it is not set for host?
"other ipclaims aren't rescheduled" - should they be rescheduled due to some other changes?

**Comment by AlexeyKasatkin** [comment]
This https://github.com/kubernetes/kubernetes/issues/4041 can probably be related.

**Comment by somejfn** [comment]
Any plan to make an official release with that fix ?  We just had the problem and I used the fix_unmarshal_err_1 docker image pushed a few days ago... otherwise the claimcontroller was in CrashLoop.

**Comment by AlexeyKasatkin** [comment]
Ops. You're right. I thought it is in "latest" already. And we'll make it a release for sure.

**Comment by AlexeyKasatkin** [comment]
@somejfn Please try using "release-0.2.2" tag.
