### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by dshulyak** [Mirantis/k8s-externalipcontroller#33]
Ubuntu size is ~200MB, ipcontroller binary is about ~27MB. For some reasons resulting image is 917 MB, which is strange. Need to debug it and reduce image size to normal one.

**Comment by dshulyak** [comment]
We need to build binary in separate image with golang:1.7, place it to _output.
And then just copy that binary to small image with debian or maybe alpine.

**Comment by pigmej** [comment]
Then you probalby cannot use dockerhub to build images... that's a drawback of that solution (known problem for virtlet and appcontroller)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Dmitry ShulyakSent: środa, 9 listopada 2016 10:58To: Mirantis/k8s-externalipcontrollerReply To: Mirantis/k8s-externalipcontrollerSubject: Re: [Mirantis/k8s-externalipcontroller] Reduce image size (#33)We need to build binary in separate image with golang:1.7, place it to _output.
And then just copy that binary to small image with debian or maybe alpine.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mirantis/k8s-externalipcontroller","title":"Mirantis/k8s-externalipcontroller","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Mirantis/k8s-externalipcontroller"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dshulyak in #33: We need to build binary in separate image with golang:1.7, place it to _output.\r\nAnd then just copy that binary to small image with debian or maybe alpine."}],"action":{"name":"View Issue","url":"https://github.com/Mirantis/k8s-externalipcontroller/issues/33#issuecomment-259495370"}}}<
 /script><br><!--end of _originalContent --></div>

**Comment by adidenko** [comment]
Guys, just use two separate containers/dockerfiles, one for build (may be based on the current image) and the other one to ship the binary (alpine or even busybox).

**Comment by dshulyak** [comment]
That what i suggested to do

**Comment by dshulyak** [comment]
@pigmej What is the problem with dockerhub? I reduced image size to 170MB, but thats because i am still using debian jessie. If one wants to reduce image size to the size of the binary it is possible to use alpine linux. But all those images are from dockerhub
